name: SupPixelCore
main: xyz.suppixel.SupPixelCore.SupPixelCore
version: 1.0
depend: [PowerfulPerms]
commands:
    spawn:
        description: text
    mem:
        description: more text
    getprefix:
        description: even more text
    sun:
        description: just even more text
    day:
        description: omfg just even more text