name: SupPixelCore
main: xyz.suppixel.SupPixelCore.SupPixelCore
version: 1.0
softdepend: [PowerfulPerms]
commands:
    spawn:
        description: text
    mem:
        description: more text
    getprefix:
        description: even more text
    sun:
        description: just even more text
    day:
        description: omfg just even more text
    glowrainbow:
        description: omfdasdsajust even more text
    glowrainbowadmin:
        description: nuuuuuu omfdasdsajust even more text
    rick:
        description: rick is een pik
    online:
        description: online gekkies
    skin:
        description: kies je skin